name: Build and Package Rust Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Rust Binary
      run: |
        cargo build --release

    - name: Package Binary as Artifact
      uses: actions/upload-artifact@v4 
      with:
        name: optimized-rust-binary
        path: target/release/ids706-indvidual2
